#!/bin/sh
clear_history() {
    for USERHOME in /home/*/; do
        for f in .config/cmus/command-history .config/cmus/search-history bash_history history lesshst mysql_history nano_history python_history recently-used ssh/known_hosts wget-hsts wpa_cli_history; do
            [ -f $USERHOME/.$f ] && rm $USERHOME/.bash_history
        done
    done
    for f in btmp faillog journal lastlog syslog wtmp; do
        [ -f /var/log/$f ] && >/var/log/$f
    done
    journalctl --vacuum-size=1B
}