#!/bin/sh
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y git wget curl dnsutils nmap masscan
export PATH=$PATH:/usr/local/go/bin            && printf "\nexport PATH=$PATH:/usr/local/go/bin\n"            >> ~/.bashrc
export PATH=$PATH:/home/acidvegas/.pdtm/go/bin && printf "\nexport PATH=$PATH:/home/acidvegas/.pdtm/go/bin\n" >> ~/.bashrc
source $HOME/.bashrc
wget -O gosource.tar.gz https://go.dev/dl/go1.21.4.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf gosource.tar.gz && rm gosource.tar.gz
mkdir -p $HOME/git
git clone https://github.com/blechschmidt/massdns.git $HOME/git/massdns && cd git/massdns && make && sudo make install && cd
git clone https://github.com/projectdiscovery/nuclei-templates.git $HOMEgit/nuclei-templates
go install -v github.com/projectdiscovery/pdtm/cmd/pdtm@latest
pdtm -ia



