#!/bin/sh
# requires: id3v2 python-eyed3
# this script removes all id3 tags/album art & sets 'artist' to the directory name & 'song' to the file name
find $HOME/music -type f | while read SONG; do
	DIR=$(dirname "$SONG")
	ARTIST=$(basename "$DIR")
	TITLE=$(basename "$SONG" | rev | cut -d"." -f2- | rev)
	echo "$DIR | $ARTIST | $TITLE"
	eyeD3 --remove-all-images "$SONG"
	id3v2 --delete-all "$SONG"
	id3v2 --artist "$ARTIST" --song "$TITLE" -2 "$SONG"
done