#!/bin/env bash
# Author: perp
# Description: Scrape free proxies

URLS=(
    # SOCKS5
    "https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5&timeout=10000&country=all"
    "https://www.proxyscan.io/download?type=socks5"
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt"
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt"
    "https://raw.githubusercontent.com/RX4096/proxy-list/main/online/socks5.txt"
    "https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks5.txt"
    "https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt"
    "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks5.txt"

    # SOCKS4
    "https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks4&timeout=10000&country=all"
    "https://www.proxyscan.io/download?type=socks4"
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt"
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt"
    "https://raw.githubusercontent.com/RX4096/proxy-list/main/online/socks4.txt"
    "https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txt"
    "https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt"
    "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks4.txt"

    # HTTP
    "https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http&timeout=10000&country=all"
    "https://www.proxyscan.io/download?type=http"
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt"
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt"
    "https://raw.githubusercontent.com/RX4096/proxy-list/main/online/http.txt"
    "https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/http.txt"
    "https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt"

    # HTTPS
    "https://api.proxyscrape.com/v2/?request=displayproxies&protocol=https&timeout=10000&country=all"
    "https://www.proxyscan.io/download?type=https"
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt"
    "https://raw.githubusercontent.com/RX4096/proxy-list/main/online/https.txt"
    "https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt"

    # MIXED
    "https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt"
    "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/http.txt"
)

# Remove proxies file
rm -f -- proxies.txt 

# Go through each URL
for URL in "${URLS[@]}";
do
    # Curl & append to file
    echo "Downloading from $URL"
    curl -s $URL >> proxies.txt &
done
wait

# Sort the uniques
sort -u -o proxies.txt proxies.txt

echo "Finished downloading proxies"
