#! /bin/sh
BLUE='\033[1;34m'
CYAN='\033[0;36m'
GREY='\033[1;30m'
RESET='\033[0m'
YELLOW='\033[0;33m'
echo -e "\n[${BLUE}CONTACT${RESET}]"
echo -e " ${GREY}* ${CYAN}E-Mail${YELLOW}\tacid.vegas@acid.vegas"
echo -e " ${GREY}* ${CYAN}Github${YELLOW}\thttps://github.com/acidvegas"
echo -e " ${GREY}* ${CYAN}IRC${YELLOW}\t\tirc.supernets.org #acidbox"
echo -e " ${GREY}* ${CYAN}Keybase${YELLOW}\thttps://keybase.io/acidvegas"
echo -e " ${GREY}* ${CYAN}Twitter${YELLOW}\thttps://twitter.com/acidvegas\n"
