#! /bin/sh
BLUE='\033[1;34m'
CYAN='\033[0;36m'
GREY='\033[1;30m'
RESET='\033[0m'
YELLOW='\033[0;33m'
echo -e "\n[${BLUE}VIRTUAL HOSTS${RESET}]"
echo -e " ${GREY}* ${CYAN}ip address 1 ${YELLOW}\tvirtual.hostname1.com"
echo -e " ${GREY}* ${CYAN}ip address 2 ${YELLOW}\tvirtual.hostname2.com"
echo -e " ${GREY}* ${CYAN}ip address 3 ${YELLOW}\tvirtual.hostname3.com"
echo -e " ${GREY}* ${CYAN}ip address 4 ${YELLOW}\tvirtual.hostname4.com"
echo -e " ${GREY}* ${CYAN}ip address 5 ${YELLOW}\tvirtual.hostname5.com\n"
