[package]
name = "irc"
version = "0.1.0"
author = "wrk"
edition = "2021"

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
typemap_rev = "0.3.0"
native-tls = "0.2.11"
