[package]
name = "drugwars"
author = "wrk"
version = "0.1.0"
edition = "2021"

[dependencies]
irc = { path = "../irc" }
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
itertools = "0.10.5"
rand = "0.8.5"
rand_distr = "0.4.3"
chrono = "0.4.24"
